apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-feedback
  namespace: sa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-feedback
  template:
    metadata:
      labels:
        app: customer-feedback
    spec:
      containers:
      - name: customer-feedback
        image: faraz2079/customer-feedback:latest
        ports:
        - containerPort: 8000
        env:
        - name: WORKERS
          value: "2"
