apiVersion: v1
kind: Service
metadata:
  name: customer-feedback-service
  namespace: sa
spec:
  selector:
    app: customer-feedback
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
